# do not install anything extra onto the image
language: generic

# use a Mac OSX image
os: osx

# only run builds on pushes to the master branch
branches:
  only:
  - master

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

# run the script to download and install Unity editor
install:
- sudo -E sh ./CIScripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./CIScripts/build.sh

# # run the script to upload the builds as tarballs
# after_success:
# - sudo -E sh ./Scripts/post_build.sh

# deploy to netlify
after_success: 
   - sudo -E sh ./CIScripts/deploy.sh

# environment variables used in bash scripts
env:
  global:
  - UNITYCI_PROJECT_NAME="unity-ci-test"
  